#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PLAYER="$ROOT/sonix-player"
WORK="${SONIX_SMOKE_DIR:-$ROOT/build/audiobook-host-smoke}"
RUN="$WORK/run"
SD="$WORK/sd"
CONFIG="$WORK/device_config.ini"
ASOUND="$WORK/asound.conf"
DB="$SD/.local/audiobooks.db"
DISPLAY_FILE="$WORK/x-display"
PLAYER_PID=""
XVFB_PID=""
WINDOW=""

fail() {
	printf 'audiobook smoke test: %s\n' "$*" >&2
	exit 1
}

need() {
	command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

stop_player() {
	if [[ -n "$PLAYER_PID" ]] && kill -0 "$PLAYER_PID" 2>/dev/null; then
		kill -TERM "$PLAYER_PID" 2>/dev/null || true
		wait "$PLAYER_PID" 2>/dev/null || true
	fi
	PLAYER_PID=""
	WINDOW=""
}

cleanup() {
	stop_player
	if [[ -n "$XVFB_PID" ]] && kill -0 "$XVFB_PID" 2>/dev/null; then
		kill -TERM "$XVFB_PID" 2>/dev/null || true
		wait "$XVFB_PID" 2>/dev/null || true
	fi
}
trap cleanup EXIT INT TERM

wait_for() {
	local description=$1
	local attempts=$2
	shift 2
	for ((i = 0; i < attempts; i++)); do
		if "$@"; then
			return 0
		fi
		sleep 0.1
	done
	fail "timed out waiting for $description"
}

catalog_ready() {
	[[ -f "$DB" ]] && [[ $(sqlite3 "$DB" 'SELECT COUNT(*) FROM AUDIOBOOK_TABLE;' 2>/dev/null) == 2 ]]
}

parts_ready() {
	[[ $(sqlite3 "$DB" "SELECT COUNT(*) FROM AUDIOBOOK_PARTS WHERE book LIKE '%/Book One';" 2>/dev/null) == 2 ]]
}

checkpoint_ready() {
	local seconds
	seconds=$(sqlite3 "$DB" "SELECT resume_pos FROM AUDIOBOOK_TABLE WHERE name='Book One';" 2>/dev/null)
	awk -v seconds="$seconds" 'BEGIN { exit !(seconds >= 10) }'
}

click() {
	xdotool mousemove --window "$WINDOW" "$1" "$2" click 1
	sleep "${3:-0.4}"
}

screenshot() {
	scrot "$WORK/$1.png"
}

start_player() {
	local run_name=$1
	local log="$WORK/$run_name.log"
	local stdout="$WORK/$run_name.stdout"

	(
		cd "$RUN"
		exec env \
			SONIX_SD_ROOT="$SD" \
			SONIX_CONFIG="$CONFIG" \
			SONIX_EBOOK_CONFIG="$WORK/ebook_config.ini" \
			SONIX_LOG="$log" \
			ALSA_CONFIG_PATH="$ASOUND" \
			./sonix_player_host >"$stdout" 2>&1
	) &
	PLAYER_PID=$!

	wait_for "the simulator process" 30 kill -0 "$PLAYER_PID"
	for ((i = 0; i < 100; i++)); do
		WINDOW=$(xdotool search --onlyvisible --pid "$PLAYER_PID" 2>/dev/null | head -n 1 || true)
		[[ -n "$WINDOW" ]] && break
		sleep 0.1
	done
	[[ -n "$WINDOW" ]] || fail "the simulator window did not appear; see $stdout"
	sleep 1
}

for command in ffmpeg make scrot sqlite3 Xvfb xdotool; do
	need "$command"
done

# Upstream's Makefile passes its checkout path to GCC without shell quoting.
# Detect that limitation here so a developer gets a useful error instead of a
# page of broken -I arguments.
[[ "$ROOT" != *' '* ]] || fail "the checkout path contains spaces; move it before running the host build"

case "$WORK" in
	"$ROOT"/build/*) rm -rf -- "$WORK" ;;
	*) fail "refusing to replace an output directory outside $ROOT/build" ;;
esac
mkdir -p "$RUN/usr/resource" \
	"$SD/Audiobooks/Test Author/Series One/Book One" \
	"$SD/Audiobooks/Standalone Author/Standalone Book"

if [[ ${SONIX_SMOKE_SKIP_BUILD:-0} != 1 ]]; then
	make -C "$PLAYER" host -j2
fi
[[ -x "$PLAYER/sonix_player_host" ]] || fail "host binary is missing; run make -C sonix-player host"
cp "$PLAYER/sonix_player_host" "$RUN/"
cp -a "$ROOT/sonix-packer/assets/R1/usr/resource/." "$RUN/usr/resource/"

cat >"$CONFIG" <<EOF
# Generated by tools/audiobook-host-smoke.sh.
[player]
playback_mode = 0
volume = 40

[audio]
gapless = 1

[ui]
language = English

[clock]
utc_offset_minutes = 0
last_seen = $(date +%s)
configured = 1
EOF

cat >"$ASOUND" <<'EOF'
pcm.!default {
  type null
}
ctl.!default {
  type hw
  card 0
}
EOF

ffmpeg -hide_banner -loglevel error -f lavfi -i "sine=frequency=440:duration=16" \
	-ac 1 -b:a 64k -metadata album="Book One" -metadata album_artist="Test Author" \
	-metadata artist="Test Author" -metadata title="Part One" -metadata track="1/2" \
	"$SD/Audiobooks/Test Author/Series One/Book One/01 - Part One.mp3"
ffmpeg -hide_banner -loglevel error -f lavfi -i "sine=frequency=550:duration=60" \
	-ac 1 -b:a 64k -metadata album="Book One" -metadata album_artist="Test Author" \
	-metadata artist="Test Author" -metadata title="Part Two" -metadata track="2/2" \
	"$SD/Audiobooks/Test Author/Series One/Book One/02 - Part Two.mp3"
ffmpeg -hide_banner -loglevel error -f lavfi -i "sine=frequency=660:duration=60" \
	-ac 1 -c:a aac -b:a 64k -metadata album="Standalone Book" \
	-metadata album_artist="Standalone Author" -metadata artist="Standalone Author" \
	-metadata title="Standalone Book" \
	"$SD/Audiobooks/Standalone Author/Standalone Book/Standalone Book.m4b"

# Use a loopback TCP display rather than /tmp/.X11-unix. WSLg exposes that
# socket directory read-only and without the sticky bit Xvfb requires, while a
# private CI runner may already have a display socket. Xvfb chooses a free
# display number and accepts connections only for the lifetime of this test.
Xvfb -nolisten unix -listen tcp -ac -displayfd 3 -screen 0 600x900x24 \
	>"$WORK/xvfb.stdout" 2>"$WORK/xvfb.log" 3>"$DISPLAY_FILE" &
XVFB_PID=$!
wait_for "Xvfb display assignment" 50 test -s "$DISPLAY_FILE"
export DISPLAY="localhost:$(cat "$DISPLAY_FILE")"

start_player first-run

# Coordinates are relative to the 480x800 R1 SDL window. The assertions below
# verify the resulting state, so an upstream layout change fails loudly instead
# of reporting a false pass.
click 355 420       # Home -> Audiobooks
click 438 88        # options button
click 240 740       # Scan Audiobooks
click 330 475       # confirmation -> Scan

wait_for "two scanned audiobooks" 300 catalog_ready
wait_for "two multipart rows" 50 parts_ready
screenshot catalog

click 240 735       # scan result -> OK
click 125 245       # Audiobooks -> Library
click 240 180       # Book One
wait_for "multipart playback" 100 grep -q "01 - Part One.mp3" "$WORK/first-run.log"
sleep 12
xdotool key --window "$WINDOW" n

wait_for "a persisted resume checkpoint" 100 checkpoint_ready
RESUME_POSITION=$(sqlite3 "$DB" "SELECT printf('%.1f', resume_pos) FROM AUDIOBOOK_TABLE WHERE name='Book One';")
RESUME_FILE=$(sqlite3 "$DB" "SELECT resume_file FROM AUDIOBOOK_TABLE WHERE name='Book One';")
[[ "$RESUME_FILE" == *"01 - Part One.mp3" ]] || fail "checkpoint selected the wrong multipart file: $RESUME_FILE"
screenshot checkpoint

stop_player
start_player resume-run
click 355 420       # Home -> Audiobooks
click 355 465       # Audiobooks -> Continue
click 240 180       # Book One

wait_for "direct resume after restart" 100 grep -Eq \
	"play requested '.*01 - Part One\\.mp3' from [1-9][0-9]*(\\.[0-9]+)? s" "$WORK/resume-run.log"
screenshot resumed

# Part one has only a few seconds left after the restored position. Its natural
# end must wake the queue immediately and start part two; the old 500 ms UI poll
# raced the 600 ms gapless hold and regularly lost that handoff for MP3.
wait_for "event-driven multipart auto-advance" 100 grep -q "starting '.*02 - Part Two.mp3'" "$WORK/resume-run.log"
grep -q "gapless: reusing the open PCM" "$WORK/resume-run.log" || \
	fail "multipart MP3 advanced, but the gapless PCM was closed between parts"

printf 'Audiobook host smoke test passed.\n'
printf '  Books: 2 (one multipart MP3, one M4B)\n'
printf '  Resume: %s at %s seconds\n' "$RESUME_FILE" "$RESUME_POSITION"
printf '  Auto-advance: multipart MP3 part one -> part two\n'
printf '  Artifacts: %s\n' "$WORK"
